# Generated by Django 2.2.28 on 2023-03-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notifications_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='type',
            field=models.CharField(choices=[('MESSAGE', 'MESSAGE'), ('HORSE LIKE', 'HORSE LIKE'), ('HORSE REPORT', 'HORSE REPORT'), ('HORSE REVIEW', 'HORSE REVIEW')], default='MESSAGE', max_length=100),
        ),
    ]
