# Generated by Django 2.2.28 on 2022-11-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_auto_20221101_0419"),
    ]

    operations = [
        migrations.AddField(
            model_name="pushnotificationsadmin",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
