# Generated by Django 2.2.28 on 2022-11-05 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_pushnotificationsadmin_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pushnotificationsadmin",
            options={"verbose_name_plural": "Push Notifications"},
        ),
    ]
