# Generated by Django 2.2.28 on 2023-01-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_auto_20221105_0703"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="message_profile_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
