version: "3.9"

services:
  web:
    build:
      context: .
      args:
        SECRET_KEY: ${SECRET_KEY}
    env_file: .env
    volumes:
      - ./:/opt/webapp
    ports:
      - "8000:${PORT}"
  postgres:
    environment:
      POSTGRES_PASSWORD: <postgres_pwd>
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    ports:
      - "6379:6379"
  
  # celeryworker:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   depends_on:
  #     - redis
  #     - postgres
  #   command: celery -A <project_name> worker -l INFO

  # celerybeat:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   depends_on:
  #     - redis
  #   ports: []
  #   command: celery -A <project_name> beat -l INFO
  
  # flower:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   env_file: .env
  #   ports:
  #     - "5555:5555"
  #   command: celery -A <project_name>.celery -b "${REDIS_URL}" flower --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"

volumes: 
  postgres-data:

