# Generated by Django 2.2.28 on 2022-11-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="message",
        ),
        migrations.AddField(
            model_name="conversation",
            name="channel",
            field=models.CharField(default="abc", max_length=100),
            preserve_default=False,
        ),
    ]
