# Generated by Django 2.2.28 on 2023-08-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20230224_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
