# Generated by Django 2.2.28 on 2022-11-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_auto_20221124_1147"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messages",
            name="file",
        ),
        migrations.RemoveField(
            model_name="messages",
            name="message",
        ),
        migrations.RemoveField(
            model_name="messages",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="messages",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="messages",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="conversation",
            name="message",
            field=models.ManyToManyField(related_name="messages", to="chat.Messages"),
        ),
        migrations.AddField(
            model_name="messages",
            name="message_timestamp",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
