# Generated by Django 2.2.28 on 2023-01-27 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_messages_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
