# Generated by Django 2.2.28 on 2023-01-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_messages_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="read_status",
            field=models.BooleanField(default=False),
        ),
    ]
