# Generated by Django 2.2.28 on 2023-01-28 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_messages_read_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messages",
            name="message_timestamp",
        ),
    ]
