# Generated by Django 2.2.28 on 2023-01-29 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_remove_messages_message_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="message",
        ),
        migrations.AddField(
            model_name="conversation",
            name="message",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.Messages",
            ),
            preserve_default=False,
        ),
    ]
