# Generated by Django 2.2.28 on 2023-01-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_auto_20230129_1122"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="channel",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
