# Generated by Django 2.2.28 on 2023-01-29 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_messages_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.Messages",
            ),
        ),
    ]
