# Generated by Django 2.2.28 on 2023-01-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_auto_20230129_1138"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="message",
            new_name="last_message",
        ),
    ]
