# Generated by Django 2.2.28 on 2023-02-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20230129_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user_one_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_two_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
