# Generated by Django 2.2.28 on 2023-02-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20230216_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedConversationsId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=100)),
            ],
        ),
    ]
