# Generated by Django 2.2.28 on 2023-02-16 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0013_deletedconversationsid'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedconversationsid',
            name='user_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_Conversation_userone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deletedconversationsid',
            name='user_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_Conversation_usertwo', to=settings.AUTH_USER_MODEL),
        ),
    ]
