# Generated by Django 2.2.28 on 2023-02-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20230216_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='read_status',
        ),
        migrations.AddField(
            model_name='messages',
            name='timetoken',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
