# Generated by Django 2.2.28 on 2023-02-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_auto_20230216_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='sender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
