from django.urls import path
from .viewsets import (
    ContactUsView,
    ReportView,
    favouriteView,
    HorseImagesView,
    KeywordsView,
    HorseView,
    HorsesView,
    searchHorseView,
    userSearchView,
    likeHorseView,
    dislikeHorseView,
    temperamentView,
    disciplineView,
    colorView,
    BreedView,
    getRecentlyAddedHorsesView,
    getTopHorseAddsView,
    getTrendingHorseAddsView,
    getDistanceBetweenUserAndHorseView,
    searchHorsesByNameView,
    AllHorsesView,
)


urlpatterns = [
    path("contactus/", ContactUsView, name="contactus"),
    path("horse-images/", HorseImagesView, name="horse-images"),
    path("keywords/", KeywordsView, name="keywords"),
    path("horse/", HorseView, name="horse"),
    path("horses/", HorsesView, name="horses"),
    path("all-horses-lat-lng/", AllHorsesView, name="AllHorsesView"),
    path("favourite/", favouriteView, name="favourite"),
    path("search-horse/", searchHorseView, name="search-horse"),
    path("user-saved-search/", userSearchView, name="user-saved-search"),
    path("user-search-by-name/", searchHorsesByNameView, name="user-search-by-name"),
    path("like-horse/", likeHorseView, name="like-horse"),
    path("dislike-horse/", dislikeHorseView, name="dislike-horse"),
    path("report/", ReportView, name="report"),
    path("temperaments/", temperamentView, name="temperament"),
    path("disciplines/", disciplineView, name="discipline"),
    path("colors/", colorView, name="colors"),
    path("breeds/", BreedView, name="breeds"),
    path("get-distance/", getDistanceBetweenUserAndHorseView, name="get-distance"),
    path(
        "recently-added-horses/",
        getRecentlyAddedHorsesView,
        name="recently-added-horses",
    ),
    path("top-horses/", getTopHorseAddsView, name="top-horses"),
    path("trending-horses/", getTrendingHorseAddsView, name="trending-horses"),
]
