# Generated by Django 2.2.28 on 2022-10-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlans",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Basic", "Basic"),
                            ("Premium", "Premium"),
                            ("Platinum", "Platinum"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("price", models.FloatField(blank=True, null=True)),
                (
                    "stripe_payment_id",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
            ],
        ),
    ]
