# Generated by Django 2.2.28 on 2022-10-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="card_number",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
