# Generated by Django 2.2.28 on 2022-10-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_auto_20221025_1905"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripecustomer",
            name="setup_intent_id",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
