# Generated by Django 2.2.28 on 2022-10-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_stripecustomer_setup_intent_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripecustomer",
            name="intent_secreat",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
