# Generated by Django 2.2.28 on 2022-10-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_stripecustomer_intent_secreat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscriptionplans",
            old_name="stripe_payment_id",
            new_name="stripe_price_id",
        ),
        migrations.AddField(
            model_name="subscriptionplans",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
