# Generated by Django 2.2.28 on 2022-10-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_auto_20221026_2330"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionplans",
            name="stripe_price_id",
        ),
        migrations.RemoveField(
            model_name="subscriptionplans",
            name="stripe_product_id",
        ),
        migrations.AddField(
            model_name="subscriptionplans",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Basic", "Basic"),
                    ("Premium", "Premium"),
                    ("Platinum", "Platinum"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplans",
            name="description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
