# Generated by Django 2.2.28 on 2022-10-27 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0010_auto_20221026_2351"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cards",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_4", models.CharField(blank=True, max_length=4, null=True)),
                ("exp_month", models.CharField(blank=True, max_length=2, null=True)),
                ("exp_year", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
