# Generated by Django 2.2.28 on 2022-10-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_cards"),
    ]

    operations = [
        migrations.AddField(
            model_name="cards",
            name="payment_id",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
