# Generated by Django 2.2.28 on 2022-10-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_cards_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplans",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
