# Generated by Django 2.2.28 on 2022-11-04 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0013_subscriptionplans_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionplans",
            options={"verbose_name_plural": "Subscription Plans"},
        ),
    ]
