# Generated by Django 2.2.28 on 2022-11-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0014_auto_20221104_0945"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripesetupintent",
            name="ephemeral_key",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
