# Generated by Django 2.2.28 on 2022-11-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0015_stripesetupintent_ephemeral_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="cards",
            name="message",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
