# Generated by Django 2.2.26 on 2023-01-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0016_cards_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplans",
            name="description_features",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="subscriptionplans",
            name="description",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
