# Generated by Django 2.2.26 on 2023-01-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0017_auto_20230117_2301"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplans",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
