# Generated by Django 2.2.26 on 2023-01-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0018_subscriptionplans_stripe_price_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplans",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
