# Generated by Django 2.2.26 on 2023-01-19 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0019_subscriptionplans_stripe_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentshistory",
            name="amount",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="paymentshistory",
            name="card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.Cards",
            ),
        ),
        migrations.AddField(
            model_name="paymentshistory",
            name="payment_intent_id",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="paymentshistory",
            name="stripe_invoice_id",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="paymentshistory",
            name="stripe_receipt_link",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
