# Generated by Django 2.2.26 on 2023-01-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_auto_20230119_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
