# Generated by Django 2.2.26 on 2023-01-16 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="horses",
            name="age",
        ),
    ]
