# Generated by Django 2.2.26 on 2023-01-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horses',
            name='height',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
    ]
