# Generated by Django 2.2.26 on 2023-01-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230120_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horses',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
