# Generated by Django 2.2.26 on 2023-01-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20230121_0803"),
    ]

    operations = [
        migrations.AddField(
            model_name="horseimages",
            name="file_type",
            field=models.CharField(
                choices=[("IMAGE", "IMAGE"), ("VIDEO", "VIDEO")],
                default="IMAGES",
                max_length=10,
            ),
        ),
    ]
