# Generated by Django 2.2.26 on 2022-10-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_favourite_horseimages_horses_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horses',
            name='discipline',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='horses',
            name='temprament',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
