# Generated by Django 2.2.28 on 2023-02-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_horseimages_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=1000, null=True)),
                ('instagram', models.CharField(blank=True, max_length=1000, null=True)),
                ('twitter', models.CharField(blank=True, max_length=1000, null=True)),
                ('linkedIn', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='author',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='body',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
