# Generated by Django 2.2.26 on 2022-10-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20221018_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horses',
            name='height',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
