# Generated by Django 2.2.26 on 2022-10-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_auto_20221018_1249"),
    ]

    operations = [
        migrations.AddField(
            model_name="horses",
            name="dislikes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="horses",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
