# Generated by Django 2.2.26 on 2022-10-19 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0006_auto_20221019_2114"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="horses",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="horses",
            name="likes",
        ),
        migrations.CreateModel(
            name="Likes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DisLikes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="horses",
            name="dislikes",
            field=models.ManyToManyField(related_name="dislikes", to="home.DisLikes"),
        ),
        migrations.AddField(
            model_name="horses",
            name="likes",
            field=models.ManyToManyField(related_name="likes", to="home.Likes"),
        ),
    ]
