# Generated by Django 2.2.28 on 2023-02-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name_plural': 'Privacy Policy'},
        ),
        migrations.AlterModelOptions(
            name='sociallinks',
            options={'verbose_name_plural': 'Social Media Platform Links'},
        ),
        migrations.AlterModelOptions(
            name='termsandcondition',
            options={'verbose_name_plural': 'Terms And Condition'},
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='is_active',
        ),
    ]
