# Generated by Django 2.2.28 on 2023-02-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20230222_0750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
        migrations.DeleteModel(
            name='SocialLinks',
        ),
        migrations.DeleteModel(
            name='TermsAndCondition',
        ),
    ]
