# Generated by Django 2.2.28 on 2023-02-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20230222_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='horses',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
