# Generated by Django 2.2.28 on 2023-02-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_horses_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='horses',
            name='city',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
