# Generated by Django 2.2.26 on 2022-10-21 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_conversation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Spam", "Spam"),
                            ("Pornography", "Pornography"),
                            ("Self-harm", "Self-harm"),
                            ("Not for children", "Not for children"),
                            (
                                "Illegal activities (e.g. drug selling)",
                                "Illegal activities (e.g. drug selling)",
                            ),
                            ("Deceptive content", "Deceptive content"),
                        ],
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "horse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.Horses",
                    ),
                ),
            ],
        ),
    ]
