# Generated by Django 2.2.28 on 2023-02-24 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20230224_1138'),
        ('home', '0010_horses_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horses',
            name='location',
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
