# Generated by Django 2.2.26 on 2022-10-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_report_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="horses",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
