# Generated by Django 2.2.28 on 2022-10-31 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_feedback_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FeedBack",
        ),
    ]
