# Generated by Django 2.2.28 on 2022-10-31 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_delete_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privacypolicy",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
