# Generated by Django 2.2.28 on 2022-10-31 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_auto_20221031_0538"),
    ]

    operations = [
        migrations.AddField(
            model_name="horses",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="horses",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
