# Generated by Django 2.2.28 on 2022-11-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_auto_20221031_0547"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="horses",
            options={"verbose_name_plural": "Horses"},
        ),
        migrations.AddField(
            model_name="report",
            name="reviewed",
            field=models.BooleanField(default=False),
        ),
    ]
