# Generated by Django 2.2.28 on 2022-11-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_auto_20221110_1750"),
    ]

    operations = [
        migrations.AlterField(
            model_name="horses",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True, related_name="dislikes", to="home.DisLikes"
            ),
        ),
        migrations.AlterField(
            model_name="horses",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="likes", to="home.Likes"
            ),
        ),
    ]
