# Generated by Django 2.2.28 on 2022-11-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_auto_20221111_1006"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keywords",
            name="keyword",
            field=models.CharField(default="abc", max_length=100),
            preserve_default=False,
        ),
    ]
