# Generated by Django 2.2.28 on 2022-11-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_auto_20221117_0845"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="email",
            field=models.EmailField(default="a", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contactus",
            name="first_name",
            field=models.CharField(default="a", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contactus",
            name="last_name",
            field=models.CharField(default="a", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contactus",
            name="query",
            field=models.TextField(default="a", max_length=1000),
            preserve_default=False,
        ),
    ]
