# Generated by Django 2.2.28 on 2022-11-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0024_auto_20221117_0909"),
    ]

    operations = [
        migrations.AlterField(
            model_name="horseimages",
            name="file",
            field=models.FileField(default="a", upload_to=""),
            preserve_default=False,
        ),
    ]
