# Generated by Django 2.2.28 on 2022-11-22 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0025_auto_20221117_1050"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messages",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="messages",
            name="sender",
        ),
        migrations.DeleteModel(
            name="Conversation",
        ),
        migrations.DeleteModel(
            name="Messages",
        ),
    ]
