# Generated by Django 2.2.28 on 2022-11-29 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0026_auto_20221122_1926"),
    ]

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("breed", models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Colors",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Disciplines",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discipline", models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Temperaments",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperament", models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="horses",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.Colors",
            ),
        ),
        migrations.AlterField(
            model_name="horses",
            name="discipline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.Disciplines",
            ),
        ),
        migrations.AlterField(
            model_name="horses",
            name="temperament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.Temperaments",
            ),
        ),
    ]
