# Generated by Django 2.2.28 on 2022-11-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0027_auto_20221129_1254"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="colors",
            options={"verbose_name_plural": "Colors"},
        ),
        migrations.AlterModelOptions(
            name="disciplines",
            options={"verbose_name_plural": "Disciplines"},
        ),
        migrations.AlterModelOptions(
            name="temperaments",
            options={"verbose_name_plural": "Temperaments"},
        ),
    ]
