# Generated by Django 2.2.28 on 2022-11-29 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0028_auto_20221129_1304"),
    ]

    operations = [
        migrations.CreateModel(
            name="Breeds",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("breed", models.CharField(max_length=1000, unique=True)),
            ],
            options={
                "verbose_name_plural": "Breeds",
            },
        ),
        migrations.AlterField(
            model_name="horses",
            name="breed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.Breeds",
            ),
        ),
    ]
