# Generated by Django 2.2.28 on 2022-11-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0029_auto_20221129_1404"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Breed",
        ),
    ]
