# Generated by Django 2.2.28 on 2022-12-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0030_delete_breed"),
    ]

    operations = [
        migrations.AddField(
            model_name="horses",
            name="country",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="horses",
            name="state",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
