# Generated by Django 2.2.26 on 2023-01-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20221201_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='horses',
            name='total_views',
            field=models.BigIntegerField(default=0),
        ),
    ]
