#!/bin/bash

set -o errexit
set -o nounset


exec celery \
    -A tiny_bird_36835.celery_app \
    -b "redis://127.0.0.1:6379" \
    flower \
    --port=5555 --basic_auth="NKsqkrPPcdrcuKHNczMgSATNMLFPdAfoc:FpreAwvBNfoLnaLuhV7deT5yPNGJ2qpxU2VJ36GmZRe7Mk5FxRUjx6URnTC1lzWX"
