#!/bin/bash

set -o errexit
set -o nounset


exec celery \
    -A tiny_bird_36835.celery_app \
    -b "${REDIS_URL}" \
    flower \
    --port=5555 --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
