# Generated by Django 2.2.26 on 2022-10-19 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("terms_and_conditions", "0001_terms_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termandcondition",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
