# Generated by Django 2.2.28 on 2023-02-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms_and_conditions', '0002_auto_20221019_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termandcondition',
            name='author',
        ),
        migrations.RemoveField(
            model_name='termandcondition',
            name='body',
        ),
        migrations.RemoveField(
            model_name='termandcondition',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='termandcondition',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='termandcondition',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='termandcondition',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
