# Generated by Django 2.2.28 on 2023-02-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms_and_conditions', '0003_auto_20230222_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termandcondition',
            options={'verbose_name': 'Terms And Condition'},
        ),
    ]
