# Generated by Django 2.2.28 on 2023-03-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearchsave',
            name='radius',
            field=models.IntegerField(default=20),
        ),
    ]
