# Generated by Django 2.2.28 on 2023-04-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_usersearchsave_radius"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersearchsave",
            name="radius",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
