# Generated by Django 2.2.28 on 2023-05-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_one_signal_play_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_adds',
            field=models.BigIntegerField(default=0),
        ),
    ]
