# Generated by Django 2.2.26 on 2022-10-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20221021_1925"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="otp",
        ),
        migrations.AddField(
            model_name="user",
            name="otp_counter",
            field=models.IntegerField(default=0),
        ),
    ]
