# Generated by Django 2.2.28 on 2022-10-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_auto_20221021_1937"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Plans",
            new_name="SubscriptionPlans",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="promotion_adds",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
