# Generated by Django 2.2.28 on 2022-10-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_auto_20221024_2153"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="plan",
            new_name="subscription_plan",
        ),
        migrations.AddField(
            model_name="subscriptionplans",
            name="number_of_adds",
            field=models.IntegerField(default=0),
        ),
    ]
