# Generated by Django 2.2.28 on 2022-10-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_auto_20221024_2159"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionplans",
            name="number_of_adds",
        ),
        migrations.AlterField(
            model_name="subscriptionplans",
            name="description",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Basic", "Basic"),
                    ("Premium", "Premium"),
                    ("Platinum", "Platinum"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
