# Generated by Django 2.2.28 on 2022-10-24 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_auto_20221024_2202"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="type",
        ),
    ]
