# Generated by Django 2.2.28 on 2022-10-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_remove_userprofile_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedUsers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
