# Generated by Django 2.2.28 on 2022-10-25 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_deletedusers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="subscription_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.SubscriptionPlans",
            ),
        ),
        migrations.DeleteModel(
            name="SubscriptionPlans",
        ),
    ]
