# Generated by Django 2.2.28 on 2022-10-29 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_auto_20221029_2217"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="subscription_date",
            new_name="subscription_renew_date",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_start_date",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
