# Generated by Django 2.2.28 on 2022-11-01 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_auto_20221029_2256"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notifications",
        ),
    ]
