# Generated by Django 2.2.28 on 2022-11-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_delete_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ban_user_from_app",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="ban_user_from_posting",
            field=models.BooleanField(default=False),
        ),
    ]
