# Generated by Django 2.2.28 on 2022-11-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_auto_20221103_0759"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ban_user_from_app_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="ban_user_from_posting_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
