# Generated by Django 2.2.28 on 2022-11-04 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_auto_20221103_1208"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name_plural": "User Profile"},
        ),
    ]
