# Generated by Django 2.2.28 on 2022-11-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_auto_20221104_0945"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="ban_user_from_app",
        ),
        migrations.RemoveField(
            model_name="user",
            name="ban_user_from_app_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="ban_user_from_posting",
        ),
        migrations.RemoveField(
            model_name="user",
            name="ban_user_from_posting_date",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ban_user_from_app",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ban_user_from_app_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ban_user_from_posting",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ban_user_from_posting_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
