# Generated by Django 2.2.26 on 2023-01-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_auto_20221224_0934"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
