# Generated by Django 2.2.26 on 2023-01-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_userprofile_receive_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="subscription_adds",
            field=models.IntegerField(default=0),
        ),
    ]
