# Generated by Django 2.2.26 on 2023-01-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_userprofile_user_stripe_subscription_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="subscription_adds",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="subscription_renew_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="subscription_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
