# Generated by Django 2.2.26 on 2023-01-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_auto_20230119_1437"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="subscription_adds",
            field=models.IntegerField(default=0),
        ),
    ]
