# Generated by Django 2.2.26 on 2023-01-20 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
        ("users", "0029_auto_20230119_1437"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersearchsave",
            name="title",
        ),
        migrations.AddField(
            model_name="usersearchsave",
            name="breed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.Breeds",
            ),
        ),
        migrations.AddField(
            model_name="usersearchsave",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.Colors",
            ),
        ),
        migrations.AddField(
            model_name="usersearchsave",
            name="discipline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.Disciplines",
            ),
        ),
        migrations.AddField(
            model_name="usersearchsave",
            name="gender",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="usersearchsave",
            name="keywords",
            field=models.ManyToManyField(
                related_name="user_search_keywords", to="home.Keywords"
            ),
        ),
        migrations.AddField(
            model_name="usersearchsave",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.Locations",
            ),
        ),
        migrations.AddField(
            model_name="usersearchsave",
            name="max_age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersearchsave",
            name="max_height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersearchsave",
            name="max_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersearchsave",
            name="min_age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersearchsave",
            name="min_height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersearchsave",
            name="min_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersearchsave",
            name="temperament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.Temperaments",
            ),
        ),
    ]
