# Generated by Django 2.2.28 on 2023-02-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20230120_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='promotion_adds',
            field=models.IntegerField(default=5),
        ),
    ]
