# Generated by Django 2.2.28 on 2023-02-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20230224_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersearchsave',
            name='location_id',
        ),
        migrations.AddField(
            model_name='usersearchsave',
            name='country',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
