# Generated by Django 2.2.28 on 2023-02-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20230224_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearchsave',
            name='cities',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='usersearchsave',
            name='states',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
