# Generated by Django 2.2.28 on 2023-02-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20230224_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersearchsave',
            old_name='cities',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='usersearchsave',
            old_name='states',
            new_name='state',
        ),
    ]
