# Generated by Django 2.2.28 on 2023-02-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialLinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallinks',
            name='appleStoreLink',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sociallinks',
            name='googleStoreLink',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
