# Generated by Django 2.2.28 on 2023-02-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialLinks', '0002_auto_20230222_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinks',
            name='appleStoreLink',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='googleStoreLink',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='linkedIn',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
