# Generated by Django 2.2.28 on 2022-10-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_feedbackresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="response",
            field=models.TextField(default="null"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="FeedBackResponse",
        ),
    ]
