# Generated by Django 2.2.28 on 2022-10-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_auto_20221031_0945"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="response",
            field=models.TextField(blank=True, null=True),
        ),
    ]
